import {
  LayoutDashboard,
  Stethoscope,
  ScanLine,
  Pill,
  MessageSquareText,
  User,
  Database,
  BookOpen,
  History,
  BrainCircuit,
  FileText,
  ActivitySquare,
  Sparkles,
  Workflow,
  HeartPulse,
  ShieldCheck,
  Boxes,
  ScrollText,
  Layers,
  Network,
  Waypoints,
  Bot,
  FlaskConical,
  BadgeCheck,
  Brain,
  FileSearch,
  Library,
} from 'lucide-react'

export const NAV_ITEMS = [
  { to: '/', label: 'Dashboard', icon: LayoutDashboard, end: true },
  { to: '/copilot', label: 'Copilot Workspace', icon: Bot },
  { to: '/digital-twin', label: 'Digital Twin', icon: HeartPulse },
  { to: '/patient-context', label: 'Patient Context', icon: Brain },
  { to: '/governance', label: 'AI Governance', icon: ShieldCheck, end: true },
  { to: '/governance/pipeline', label: 'Pipeline Viewer', icon: Network },
  { to: '/governance/models', label: 'Model Registry', icon: Boxes },
  { to: '/governance/datasets', label: 'Dataset Registry', icon: Layers },
  { to: '/governance/audit-logs', label: 'Audit Logs', icon: ScrollText },
  { to: '/agents', label: 'AI Agent Monitor', icon: Workflow },
  { to: '/predict', label: 'Disease Prediction', icon: Stethoscope },
  { to: '/symptoms', label: 'Symptom Checker', icon: ActivitySquare },
  { to: '/ocr', label: 'Prescription OCR', icon: ScanLine },
  { to: '/documents', label: 'Document Intelligence', icon: FileSearch },
  { to: '/clinical', label: 'Clinical Decision', icon: BrainCircuit },
  { to: '/reasoning', label: 'Clinical Reasoning', icon: Waypoints },
  { to: '/simulator', label: 'Treatment Simulator', icon: FlaskConical },
  { to: '/verification', label: 'Evidence Verification', icon: BadgeCheck },
  { to: '/evidence', label: 'Evidence Explorer', icon: Library },
  { to: '/reports', label: 'Medical Reports', icon: FileText },
  { to: '/history', label: 'Prescription History', icon: History },
  { to: '/dataset', label: 'Dataset Evaluation', icon: Database },
  { to: '/knowledge', label: 'Knowledge Base', icon: BookOpen },
  { to: '/medicine', label: 'Medicine Search', icon: Pill },
  { to: '/recommendations', label: 'Medicine Recommendations', icon: Sparkles },
  { to: '/chat', label: 'AI Assistant', icon: MessageSquareText },
  { to: '/profile', label: 'Profile', icon: User },
]
